/* -*- c++ -*- */
/*
 * Copyright 2013 Dimitri Stolnikov <horiz0n@gmx.net>
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <gnuradio/io_signature.h>
#include <gnuradio/constants.h>

#ifdef ENABLE_UHD
#include "uhd_sink_c.h"
#endif
#ifdef ENABLE_HACKRF
#include "hackrf_sink_c.h"
#endif
#ifdef ENABLE_BLADERF
#include "bladerf_sink_c.h"
#endif
#ifdef ENABLE_SOAPY
#include "soapy_sink_c.h"
#endif
#ifdef ENABLE_REDPITAYA
#include "redpitaya_sink_c.h"
#endif
#ifdef ENABLE_FREESRP
#include <freesrp_sink_c.h>
#endif
#ifdef ENABLE_FILE
#include "file_sink_c.h"
#endif

#include "arg_helpers.h"
#include "sink_impl.h"

/*
 * Create a new instance of sink_impl and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
osmosdr::sink::sptr
osmosdr::sink::make( const std::string &args )
{
  return gnuradio::get_initial_sptr( new sink_impl(args) );
}

/*
 * The private constructor
 */
sink_impl::sink_impl( const std::string &args )
  : gr::hier_block2 ("sink_impl",
        args_to_io_signature(args),
        gr::io_signature::make(0, 0, 0)),
    _manager(make_dev_manager(to_hier_block2()))
{
  size_t channel = 0;
  bool device_specified = false;

  message_port_register_hier_in( osmosdr::CMD_PORT );
  msg_connect( self(), osmosdr::CMD_PORT, _manager, osmosdr::CMD_PORT );

  std::vector< std::string > arg_list = args_to_vector(args);

  std::vector< std::string > dev_types;

#ifdef ENABLE_UHD
  dev_types.push_back("uhd");
#endif
#ifdef ENABLE_HACKRF
  dev_types.push_back("hackrf");
#endif
#ifdef ENABLE_BLADERF
  dev_types.push_back("bladerf");
#endif
#ifdef ENABLE_SOAPY
  dev_types.push_back("soapy");
#endif
#ifdef ENABLE_REDPITAYA
  dev_types.push_back("redpitaya");
#endif
#ifdef ENABLE_FREESRP
  dev_types.push_back("freesrp");
#endif
#ifdef ENABLE_FILE
  dev_types.push_back("file");
#endif

  std::cerr << "gr-osmosdr "
            << GR_OSMOSDR_VERSION << " (" << GR_OSMOSDR_LIBVER << ") "
            << "gnuradio " << gr::version() << std::endl;
  std::cerr << "built-in sink types: ";
  BOOST_FOREACH(std::string dev_type, dev_types)
    std::cerr << dev_type << " ";
  std::cerr << std::endl;

  BOOST_FOREACH(std::string arg, arg_list) {
    dict_t dict = params_to_dict(arg);
    BOOST_FOREACH(std::string dev_type, dev_types) {
      if ( dict.count( dev_type ) ) {
        device_specified = true;
        break;
      }
    }
  }

  if ( ! device_specified ) {
    std::vector< std::string > dev_list;
#ifdef ENABLE_UHD
    BOOST_FOREACH( std::string dev, uhd_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_BLADERF
    BOOST_FOREACH( std::string dev, bladerf_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_HACKRF
    BOOST_FOREACH( std::string dev, hackrf_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_SOAPY
    BOOST_FOREACH( std::string dev, soapy_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_REDPITAYA
    BOOST_FOREACH( std::string dev, redpitaya_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_FREESRP
    BOOST_FOREACH( std::string dev, freesrp_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif
#ifdef ENABLE_FILE
    BOOST_FOREACH( std::string dev, file_sink_c::get_devices() )
      dev_list.push_back( dev );
#endif

//    std::cerr << std::endl;
//    BOOST_FOREACH( std::string dev, dev_list )
//      std::cerr << "'" << dev << "'" << std::endl;

    if ( dev_list.size() )
      arg_list.push_back( dev_list.front() );
    else
      throw std::runtime_error("No supported devices found (check the connection and/or udev rules).");
  }

  BOOST_FOREACH(std::string arg, arg_list) {

    dict_t dict = params_to_dict(arg);

//    std::cerr << std::endl;
//    BOOST_FOREACH( dict_t::value_type &entry, dict )
//      std::cerr << "'" << entry.first << "' = '" << entry.second << "'" << std::endl;

    sink_iface *iface = NULL;
    gr::basic_block_sptr block;

#ifdef ENABLE_UHD
    if ( dict.count("uhd") ) {
      uhd_sink_c_sptr sink = make_uhd_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_HACKRF
    if ( dict.count("hackrf") ) {
      hackrf_sink_c_sptr sink = make_hackrf_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_BLADERF
    if ( dict.count("bladerf") ) {
      bladerf_sink_c_sptr sink = make_bladerf_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_SOAPY
    if ( dict.count("soapy") ) {
      soapy_sink_c_sptr sink = make_soapy_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_REDPITAYA
    if ( dict.count("redpitaya") ) {
      redpitaya_sink_c_sptr sink = make_redpitaya_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_FREESRP
    if ( dict.count("freesrp") ) {
      freesrp_sink_c_sptr sink = make_freesrp_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif
#ifdef ENABLE_FILE
    if ( dict.count("file") ) {
      file_sink_c_sptr sink = make_file_sink_c( arg );
      block = sink; iface = sink.get();
    }
#endif

    _manager->add_device( block, iface );
  }

  if (!_manager->get_num_mboards())
    throw std::runtime_error("No devices specified via device arguments.");
}

size_t sink_impl::get_num_channels()
{
  return _manager->get_num_channels();
}

osmosdr::meta_range_t sink_impl::get_sample_rates()
{
  return _manager->get_sample_rates();
}

double sink_impl::set_sample_rate( double rate )
{
  return _manager->set_sample_rate( rate );
}

double sink_impl::get_sample_rate()
{
  return _manager->get_sample_rate();
}

osmosdr::freq_range_t sink_impl::get_freq_range( size_t chan )
{
  return _manager->get_freq_range( chan );
}

double sink_impl::set_center_freq( double freq, size_t chan )
{
  return _manager->set_center_freq( freq, chan );
}

double sink_impl::get_center_freq( size_t chan )
{
  return _manager->get_center_freq( chan );
}

double sink_impl::set_freq_corr( double ppm, size_t chan )
{
  return _manager->set_freq_corr( ppm, chan );
}

double sink_impl::get_freq_corr( size_t chan )
{
  return _manager->get_freq_corr( chan );
}

std::vector<std::string> sink_impl::get_gain_names( size_t chan )
{
  return _manager->get_gain_names( chan );
}

osmosdr::gain_range_t sink_impl::get_gain_range( size_t chan )
{
  return _manager->get_gain_range( chan );
}

osmosdr::gain_range_t sink_impl::get_gain_range( const std::string & name, size_t chan )
{
  return _manager->get_gain_range( name, chan );
}

bool sink_impl::set_gain_mode( bool automatic, size_t chan )
{
  return _manager->set_gain_mode( automatic, chan );
}

bool sink_impl::get_gain_mode( size_t chan )
{
  return _manager->get_gain_mode( chan );
}

double sink_impl::set_gain( double gain, size_t chan )
{
  return _manager->set_gain( gain, chan );
}

double sink_impl::set_gain( double gain, const std::string & name, size_t chan)
{
  return _manager->set_gain( gain, name, chan );
}

double sink_impl::get_gain( size_t chan )
{
  return _manager->get_gain( chan );
}

double sink_impl::get_gain( const std::string & name, size_t chan )
{
  return _manager->get_gain( name, chan );
}

double sink_impl::set_if_gain( double gain, size_t chan )
{
  return _manager->set_if_gain( gain, chan );
}

double sink_impl::set_bb_gain( double gain, size_t chan )
{
  return _manager->set_bb_gain( gain, chan );
}

std::vector< std::string > sink_impl::get_antennas( size_t chan )
{
  return _manager->get_antennas( chan );
}

std::string sink_impl::set_antenna( const std::string & antenna, size_t chan )
{
  return _manager->set_antenna( antenna, chan );
}

std::string sink_impl::get_antenna( size_t chan )
{
  return _manager->get_antenna( chan );
}

void sink_impl::set_dc_offset( const std::complex<double> &offset, size_t chan )
{
  _manager->set_dc_offset( offset, chan );
}

void sink_impl::set_iq_balance( const std::complex<double> &balance, size_t chan )
{
  _manager->set_iq_balance( balance, chan );
}

double sink_impl::set_bandwidth( double bandwidth, size_t chan )
{
  return _manager->set_bandwidth( bandwidth, chan );
}

double sink_impl::get_bandwidth( size_t chan )
{
  return _manager->get_bandwidth( chan );
}

osmosdr::freq_range_t sink_impl::get_bandwidth_range( size_t chan )
{
  return _manager->get_bandwidth_range( chan );
}

void sink_impl::set_time_source( const std::string &source, const size_t mboard )
{
  return _manager->set_time_source( source, mboard );
}

std::string sink_impl::get_time_source( const size_t mboard )
{
  return _manager->get_time_source( mboard );
}

std::vector<std::string> sink_impl::get_time_sources( const size_t mboard )
{
  return _manager->get_time_sources( mboard );
}

void sink_impl::set_clock_source( const std::string &source, const size_t mboard )
{
  return _manager->set_clock_source( source, mboard );
}

std::string sink_impl::get_clock_source( const size_t mboard )
{
  return _manager->get_clock_source( mboard );
}

std::vector<std::string> sink_impl::get_clock_sources( const size_t mboard )
{
  return _manager->get_clock_sources( mboard );
}

double sink_impl::get_clock_rate( size_t mboard )
{
  return _manager->get_clock_rate( mboard );
}

void sink_impl::set_clock_rate( double rate, size_t mboard )
{
  return _manager->set_clock_rate( rate, mboard );
}

osmosdr::time_spec_t sink_impl::get_time_now( size_t mboard )
{
  return _manager->get_time_now( mboard );
}

osmosdr::time_spec_t sink_impl::get_time_last_pps( size_t mboard )
{
  return _manager->get_time_last_pps( mboard );
}

void sink_impl::set_time_now( const osmosdr::time_spec_t &time_spec, size_t mboard )
{
  return _manager->set_time_now( time_spec, mboard );
}

void sink_impl::set_time_next_pps( const osmosdr::time_spec_t &time_spec )
{
  return _manager->set_time_next_pps( time_spec );
}

void sink_impl::set_time_unknown_pps( const osmosdr::time_spec_t &time_spec )
{
  return _manager->set_time_unknown_pps( time_spec );
}
